### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by yannickl** [yannickl/Reactions#2]
# Features:

- [ ] animated icons support (like facebook)
- [ ] improve the hide/dismiss `ReactionSelector` animation when a `ReactionButton` is pushed to look like Facebook ones
- [ ] the `ReactionSelector` should always appears inside the screen bounds (e.g. top or bottom)
